export const satelliteList = [
    {id:"DLR-TUBSAT", country:"Germany", launch_date:"26-05-1999", mass:"45", launcher:"PSLV-C2"},
    {id:"KITSAT-3", country:"REPUBLIC OF KOREA", launch_date:"26-05-1999",mass:"110",launcher:"PSLV-C2"},
    {id:"BIRD", country:"GERMANY", launch_date:"22-10-2001", mass:"92", launcher:"PSLV-C3"},
    {id:"PROBA", country:"BELGIUM", launch_date:"22-10-2001", mass:"94", launcher:"PSLV-C3"},
    {id:"LAPAN-TUBSAT", country:"INDONESIA", launch_date:"10-07-2007", mass:"56", launcher:"PSLV-C7"},
    {id:"PEHUENSAT-1", country:"ARGENTINA",launch_date:"10-07-2007",mass:"6",launcher:"PSLV-C7"},
    {id:"AGILE",country:"ITALY",launch_date:"23-04-2007", mass:"350",launcher:"PSLV-C8"},
    {id:"TESCAR", country:"ISRAEL", launch_date:"21-01-2008", mass:"300", launcher:"PSLV-C10"},
    {id:"CAN-X2", country:"CANADA", launch_date:"28-04-2008", mass:"7", launcher:"PSLV-C9"},
    {id:"CUTE-1.7", country:"JAPAN", launch_date:"28-04-2008", mass:"5", launcher:"PSLV-C9"},
    {id:"DELFI-C3", country:"THE NETHERLANDS", launch_date:"28-04-2008", mass:"6.5", launcher:"PSLV-C9"},
    {id:"AAUSAT-II", country:"DENMARK", launch_date:"28-04-2008", mass:"3", launcher:"PSLV-C9"},
    {id:"COMPASS-I", country:"GERMANY", launch_date:"28-04-2008", mass:"3", launcher:"PSLV-C9"},
    {id:"SEEDS", country:"JAPAN", launch_date:"28-04-2008", mass:"3", launcher:"PSLV-C9"},
    {id:"NLSS", country:"CANADA", launch_date:"28-04-2008", mass:"16", launcher:"PSLV-C9"},
    {id:"RUBIN-8", country:"GERMANY",launch_date:"28-04-2008",mass:"8",launcher:"PSLV-C9"},
    {id:"CUBESAT-1", country:"GERMANY",launch_date:"23-09-2009",mass:"1",launcher:"PSLV-C14"},
    {id:"CUBESAT-2", country:"GERMANY",launch_date:"23-09-2009",mass:"1",launcher:"PSLV-C14"},
    {id:"CUBESAT-3", country:"TURKEY",launch_date:"23-09-2009",mass:"1",launcher:"PSLV-C14"},
    {id:"CUBESAT-4", country:"SWITZERLAND",launch_date:"23-09-2009",mass:"1",launcher:"PSLV-C14"},
    {id:"RUBIN-9.1", country:"GERMANY",launch_date:"23-09-2009",mass:"1",launcher:"PSLV-C14"},
    {id:"RUBIN-9.2", country:"GERMANY",launch_date:"23-09-2009",mass:"1",launcher:"PSLV-C14"},
    {id:"ALSAT-2A", country:"ALGERIA",launch_date:"12-07-2010",mass:"116",launcher:"PSLV-C15"},
    {id:"NLS6.1 AISSAT-1", country:"NORWAY",launch_date:"12-07-2010",mass:"6.5",launcher:"PSLV-C15"},
    {id:"NLS6.2 TISAT-1", country:"SWITZERLAND",launch_date:"12-07-2010",mass:"1",launcher:"PSLV-C15"},
    {id:"X-SAT", country:"SINGAPORE",launch_date:"20-04-2011",mass:"106",launcher:"PSLV-C16"},
    {id:"VesselSat-1", country:"LUXEMBOURG",launch_date:"12-10-2011",mass:"28.7",launcher:"PSLV-C18"},
    {id:"SPOT-6", country:"FRANCE",launch_date:"09-09-2012",mass:"712",launcher:"PSLV-C21"},
    {id:"PROITERES", country:"JAPAN",launch_date:"09-09-2012",mass:"15",launcher:"PSLV-C21"},
    {id:"SAPPHIRE", country:"CANADA",launch_date:"25-02-2013",mass:"148",launcher:"PSLV-C20"},
    {id:"SPOT-7", country:"FRANCE",launch_date:"30-06-2014",mass:"714",launcher:"PSLV-C23"},
    {id:"AISAT", country:"GERMANY",launch_date:"30-06-2014",mass:"14",launcher:"PSLV-C23"},
    {id:"NLS7.1(CAN-X4)", country:"CANADA",launch_date:"30-06-2014",mass:"15",launcher:"PSLV-C23"},
    {id:"NLS7.2(CAN-X5)", country:"CANADA",launch_date:"30-06-2014",mass:"15",launcher:"PSLV-C23"},
    {id:"VELOX-1", country:"SINGAPORE",launch_date:"30-06-2014",mass:"7",launcher:"PSLV-C23"},
    {id:"AMAZONIA-1", country:"BRAZIL",launch_date:"28-02-2021",mass:"637",launcher:"PSLV-C51"},
    {id:"DMC3-1", country:"UK",launch_date:"10-07-2015",mass:"447",launcher:"PSLV-C28"},
    {id:"DMC3-2", country:"UK",launch_date:"10-07-2015",mass:"447",launcher:"PSLV-C28"},
    {id:"DMC3-3", country:"UK",launch_date:"10-07-2015",mass:"447",launcher:"PSLV-C28"},
    {id:"CBNT-1", country:"UK",launch_date:"10-07-2015",mass:"91",launcher:"PSLV-C28"},
    {id:"De-OrbitSail", country:"UK",launch_date:"10-07-2015",mass:"7",launcher:"PSLV-C28"},
    {id:"LAPAN-A2", country:"INDONESIA",launch_date:"28-09-2015",mass:"76","launcher":"PSLV-C30"},
    {id:"NLS-14(Ev9)", country:"CANADA",launch_date:"28-09-2015",mass:"14","launcher":"PSLV-C30"},
    {id:"LEMUR-1", country:"USA",launch_date:"28-09-2015",mass:"7",launcher:"PSLV-C30"},
    {id:"LEMUR-2", country:"USA",launch_date:"28-09-2015",mass:"7",launcher:"PSLV-C30"},
    {id:"LEMUR-3", country:"USA",launch_date:"28-09-2015",mass:"7",launcher:"PSLV-C30"},
    {id:"LEMUR-4", country:"USA",launch_date:"28-09-2015",mass:"7",launcher:"PSLV-C30"},
    {id:"TeLEOS",country:"SINGAPORE",launch_date:"16-12-2015",mass:"400",launcher:"PSLV-C29"},
    {id:"Kent Ridge-I",country:"SINGAPORE",launch_date:"16-12-2015",mass:"78",launcher:"PSLV-C29"},
    {id:"VELOX-C1",country:"SINGAPORE",launch_date:"16-12-2015",mass:"123",launcher:"PSLV-C29"},
    {id:"VELOX-II",country:"SINGAPORE",launch_date:"16-12-2015",mass:"13",launcher:"PSLV-C29"},
    {id:"Galassia",country:"SINGAPORE",launch_date:"16-12-2015",mass:"3.4",launcher:"PSLV-C29"},
    {id:"Athenoxat-I",country:"SINGAPORE",launch_date:"16-12-2015",mass:"",launcher:"PSLV-C29"}
]

export const launcherList = [
    {id:"SLV-3E1", category: "Satellite Launch Vehicle", status: "retired"},
    {id:"SLV-3E2", category: "Satellite Launch Vehicle", status: "retired"},
    {id:"SLV-3D1", category: "Satellite Launch Vehicle", status: "retired"},
    {id:"SLV-3", category: "Satellite Launch Vehicle", status: "retired"},
    {id:"ASLV-D1", category: "Augmented Satellite Launch Vehicle", status: "retired"},
    {id:"ASLV-D2", category: "Augmented Satellite Launch Vehicle", status: "retired"},
    {id:"ASLV-D3", category: "Augmented Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-D1", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"ASLV-D4", category: "Augmented Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-D2", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-D3", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C1", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C2", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-D1", category: "Geosynchronous Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-C3", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C4", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-D2", category: "Geosynchronous Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-C5", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F01", category: "Geosynchronous Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-C6", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F02", category: "Geosynchronous Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-C7", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C8", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F04", category: "Geosynchronous Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-C10", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C9", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C11", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C12", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C14", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-D3", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C15", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F06", category: "Geosynchronous Satellite Launch Vehicle", status: "retired"},
    {id:"PSLV-C16", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C17", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C18", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C19", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C21", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C20", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C22", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C25", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-D5", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C24", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C23", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C26", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"LVM-3", category: "Launch Vehicle Mark-3", status: "active"},
    {id:"PSLV-C27", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C28", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-D6", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C30", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C29", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C31", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C32", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C33", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"RLV-TD", category:"Reusable Launch Vehicle-Technology Demonstration Programme", status:"testing prototypes"},
    {id:"PSLV-C34", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"Scramjet Engine - TD", category: "Scramjet Engine Technology", status: "active"},
    {id:"GSLV-F05", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C35", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C36", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C37", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F09", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"GSLV Mk III-D1", category: "Launch Vehicle Mark-3", status: "active"},
    {id:"PSLV-C38", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C39", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C40", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F08", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C41", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C42", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV Mk III-D2", category: "Launch Vehicle Mark-3", status: "active"},
    {id:"PSLV-C43", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F11", category: "Geosynchronous Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C44", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C45", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C46", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-Mk III - M1", category: "Launch Vehicle Mark-3", status: "active"},
    {id:"PSLV-C47", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C48", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C49", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C50", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"PSLV-C51", category: "Polar Satellite Launch Vehicle", status: "active"},
    {id:"GSLV-F10", category: "Geosynchronous Satellite Launch Vehicle", status: "active"}
]

export const centreList = [
    {id:1,name:"Semi-Conductor Laboratory (SCL)", place:"Chandigarh", state:"Punjab/Haryana"},
    {id:2,name:"Western RRSC", place:"Jodhpur", state:"Rajasthan"},
    {id:3,name:"Solar Observatory", place:"Udaipur", state:"Rajasthan"},
    {id:4,name:"Space Applications Centre (SAC)", place:"Ahmedabad", state:"Gujarat"},
    {id:5,name:"Physical Research Laboratory (PRL)", place:"Ahmedabad", state:"Gujarat"},
    {id:6,name:"Development and Educational Communication Unit (DECU)", place:"Ahmedabad", state:"Gujarat"},
    {id:7,name:"Infrared Observatory", place:"Mt.Abu", state:"Rajasthan"},
    {id:8,name:"Master Control Facility-B (MCF)", place:"Bhopal", state:"Madhya Pradesh"},
    {id:9,name:"ISRO Liaison Office", place:"Mumbai", state:"Maharashtra"},
    {id:10,name:"Indian Deep Space Network (IDSN)", place:"Byalalu", state:"Karnataka"},
    {id:11,name:"Indian Space Science Data Centre (ISSDC)", place:"Byalalu", state:"Karnataka"},
    {id:12,name:"Master Control Facility (MCF)", place:"Hassan", state:"Karnataka"},
    {id:13,name:"Ammonium Perchlorate Experimental Plant", place:"Aluva", state:"Kerala"},
    {id:14,name:"Space Commission", place:"Bengaluru", state:"Karnataka"},
    {id:15,name:"Department of Space and ISRO Headquarters", place:"Bengaluru", state:"Karnataka"},
    {id:16,name:"INSAT Programme Office", place:"Bengaluru", state:"Karnataka"},
    {id:17,name:"NNRMS Secretariat", place:"Bengaluru", state:"Karnataka"},
    {id:18,name:"Civil Engineering Programme Office", place:"Bengaluru", state:"Karnataka"},
    {id:19,name:"Antrix Corporation", place:"Bengaluru", state:"Karnataka"},
    {id:20,name:"U R Rao Satellite Centre (URSC)", place:"Bengaluru", state:"Karnataka"},
    {id:21,name:"Laboratory for Electro-Optical Systems (LEOS)", place:"Bengaluru", state:"Karnataka"},
    {id:22,name:"ISRO Telemetry, Tracking and Command Network (ISTRAC)", place:"Bengaluru", state:"Karnataka"},
    {id:23,name:"Southern RRSC", place:"Bengaluru", state:"Karnataka"},
    {id:24,name:"Liquid Propulsion Systems Centre (LPSC)", place:"Bengaluru", state:"Karnataka"},
    {id:25,name:"Human Space Flight Centre (HSFC)", place:"Bengaluru", state:"Karnataka"},
    {id:26,name:"New Space India Limited (NSIL)", place:"Bengaluru", state:"Karnataka"},
    {id:27,name:"New Space India Limited (NSIL)", place:"New Delhi", state:"Delhi"},
    {id:28,name:"ISRO Branch Office", place:"New Delhi", state:"Delhi"},
    {id:29,name:"Delhi Earth Station", place:"New Delhi", state:"Delhi"},
    {id:30,name:"Indian Institute of Remote Sensing (IIRS)", place:"Dehradun", state:"Uttarakand"},
    {id:31,name:"Centre for Space Science and Technology Education in Asia-Pacific (CSSTEAP)", place:"Dehradun", state:"Uttarakand"},
    {id:32,name:"ISTRAC Ground Station", place:"Lucknow", state:"Uttar Pradesh"},
    {id:33,name:"Eastern RRSC", place:"Kolkata", state:"West Bengal"},
    {id:34,name:"North Eastern Space Application Centre (NE-SAC)", place:"Shillong", state:"Meghalaya"},
    {id:35,name:"Central RRSC", place:"Nagpur", state:"Maharashtra"},
    {id:36,name:"National Remote Sensing Centre (NRSC)", place:"Hyderabad", state:"Telangana"},
    {id:37,name:"National Atmospheric Research Laboratory (NARL)", place:"Tirupati", state:"Andhra Pradesh"},
    {id:38,name:"Down Range Station", place:"Port Blair", state:"Andaman and Nicobar"},
    {id:39,name:"Satish Dhawan Space Centre (SDSC), SHAR", place:"Sriharikota", state:"Andhra Pradesh"},
    {id:40,name:"ISRO Propulsion Complex", place:"Mahendragiri", state:"Tamil Nadu"},
    {id:41,name:"Vikram Sarabhai Space Centre (VSSC)", place:"Thiruvananthapuram", state:"Kerala"},
    {id:42,name:"Liquid Propulsion Systems Centre (LPSC)", place:"Thiruvananthapuram", state:"Kerala"},
    {id:43,name:"ISRO Inertial Systems Unit (IISU)", place:"Thiruvananthapuram", state:"Kerala"},
    {id:44,name:"Indian Institute of Space Science and Technology (IIST)", place:"Thiruvananthapuram", state:"Kerala"}
]